const products = [
  {
    name: 'productname',
    description: 'Card description',
    detailedDescription: 'detailed description',
    price: 100,
    discount: '1 = fullprice',
    productCategory: [1],
    productSubCategory: [1],
    inStock: 0,
    image: 'image',
    brand: 'brandname',
    itemNr: '511894',
    options: [{ types: '{size}, {colors}, {length},' }],
    reviews: [''],
    rating: 0,
  },
  {
    name: 'productname',
    description: 'description',
    detailedDescription: 'Detailed description',
    price: 150,
    discount: '1 = fullprice',
    productCategory: [2, 1],
    productSubCategory: [2],
    inStock: 0,
    image: 'image',
    brand: 'brandname',
    itemNr: '156845',
    options: [{ types: '{size}, {colors}, {length},' }],
    reviews: [''],
    rating: 0,
  },
  {
    name: 'productname',
    description: 'description',
    detailedDescription: 'Detailed description',
    price: 150,
    discount: '1 = fullprice',
    productCategory: [2],
    productSubCategory: [1],
    inStock: 0,
    image: 'image',
    brand: 'brandname',
    itemNr: '123132',
    options: [{ types: '{size}, {colors}, {length},' }],
    reviews: [''],
    rating: 0,
  },
  {
    name: 'productname',
    description: 'description',
    detailedDescription: 'Detailed description',
    price: 150,
    discount: '1 = fullprice',
    productCategory: [1, 2],
    productSubCategory: [2],
    inStock: 0,
    image: 'image',
    brand: 'brandname',
    itemNr: '179982',
    options: [{ types: '{size}, {colors}, {length},' }],
    reviews: [''],
    rating: 0,
  },
  {
    name: 'productname',
    description: 'description',
    detailedDescription: 'Detailed description',
    price: 150,
    discount: '1 = fullprice',
    productCategory: [2],
    productSubCategory: [2],
    inStock: 0,
    image: 'image',
    brand: 'brandname',
    itemNr: '956655',
    options: [{ types: '{size}, {colors}, {length},' }],
    reviews: [''],
    rating: 0,
  },
  {
    name: 'productname',
    description: 'description',
    detailedDescription: 'Detailed description',
    price: 150,
    discount: '1 = fullprice',
    productCategory: [2, 3],
    productSubCategory: [2],
    inStock: 0,
    image: 'image',
    brand: 'brandname',
    itemNr: '568744',
    options: [{ types: '{size}, {colors}, {length},' }],
    reviews: [''],
    rating: 0,
  },
  {
    name: 'productname',
    description: 'description',
    detailedDescription: 'Detailed description',
    price: 150,
    discount: '1 = fullprice',
    productCategory: [1, 2, 3],
    productSubCategory: [1, 3],
    inStock: 0,
    image: 'image',
    brand: 'brandname',
    itemNr: '642587',
    options: [{ types: '{size}, {colors}, {length},' }],
    reviews: [''],
    rating: 0,
  },
  {
    name: 'productname',
    description: 'description',
    detailedDescription: 'Detailed description',
    price: 150,
    discount: '1 = fullprice',
    productCategory: [1],
    productSubCategory: [1],
    inStock: 0,
    image: 'image',
    brand: 'brandname',
    itemNr: '177778',
    options: [{ types: '{size}, {colors}, {length},' }],
    reviews: [''],
    rating: 0,
  }
  // {
  //   name: 'productname',
  //   description: 'description',
  //   detailedDescription: 'detailed description',
  //   price: 'price = standard price x option x discount',
  //   discount: '1 = fullprice',
  //   productCategory: 2,
  //   productSubCategory: 2,
  //   inStock: 0,
  //   image: 'image',
  //   brand: 'brandname',
  //   itemNr: '',
  //   options: [{ types: '{size}, {colors}, {length},' }],
  //   reviews: [''],
  //   rating: 0,
  // }
]

export default products